### ISSUE TITLE
Unable to install Hide Private Properties from AssetLib, no files available to install

### ISSUE THREAD

**Issue by Mickeon** [kenyoni-software/godot-addons#1]
Hello, I hope it's a fine day for you. I was about to download the small "Hide Private Properties" addon from the AssetLib. It may be what I need. However, it is not possible to do so. Due of the way all these addons are exposed, no files are available to install.
![image](https://github.com/kenyoni-software/godot-addons/assets/66727710/566cefc4-aa6d-4a61-9275-3162d4dd105a)

It is not something particularly terrible for me, as I can just take inspiration from the plugin's source to create something more, but I just felt like it was worth pointing out to the creator.

**Comment by IceflowRE** [comment]
This only affects the in editor asset lib.

**Comment by IceflowRE** [comment]
https://github.com/godotengine/godot/issues/81311

**Comment by IceflowRE** [comment]
Will be fixed in Godot.
