### ISSUE TITLE
[License Manager] How to show the License Manager UI?

### ISSUE THREAD

**Issue by etherealxx** [kenyoni-software/godot-addons#15]
This UI
![image](https://github.com/user-attachments/assets/eed5b82f-0a72-435f-b2bd-c335743354fd)
How could i show it? There's no button to pop it up as far as i'm aware. double clicking the license.json on FileSystem also opens it in script editor instead of a custom UI. I already installed and activated the addon by the way.
![image](https://github.com/user-attachments/assets/0596cdac-3f13-41e0-96fd-887566176183)
I don't find any guide on the [docs page](https://kenyoni-software.github.io/godot-addons/addons/licenses). I'm confused.

**Comment by IceflowRE** [comment]
![image](https://github.com/user-attachments/assets/bed7fefe-5d53-4cbb-9304-23135b86f084)

In general you will find the most tools under Project -> Tools ...

I'll update the documentation to clarify this.
