### ISSUE TITLE
License Manager saves entire JSON file on one line

### ISSUE THREAD

**Issue by zibetnu** [kenyoni-software/godot-addons#18]
This makes it hard to read when comparing diffs and whatnot.

**Comment by IceflowRE** [comment]
Could you test the branch [licenses/indent](https://github.com/kenyoni-software/godot-addons/tree/licenses/indent)?
I added a project setting under `Plugins -> Licenses -> Indentation` to configure the license file indentation with `None`, `Spaces` and `Tabs`.

I would be happy to get any feedback!

**Comment by zibetnu** [comment]
Looks great to me! Thank you for taking the time to do that.
